CREATE TABLE ordertransaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    price_change DECIMAL(19,4) NOT NULL,
    quantity DECIMAL(19,4) NOT NULL,
    create_at TIMESTAMP,
    CONSTRAINT fk_ordertransaction_order FOREIGN KEY (order_id) REFERENCES orderbook(id)
);